const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{"content-type":"application/json; charset=utf-8"}});
const safe=v=>String(v||"").trim().toLowerCase().replace(/[^a-z0-9-_]/g,"-").replace(/-+/g,"-").slice(0,80);
async function read(env,k,f){const o=await env.MEASURE_PHOTOS.get(k);if(!o)return f;try{return JSON.parse(await o.text())}catch{return f}}
const canon=v=>v==="front"||v==="front-left"||v==="front-right"?"front":v==="rear"||v==="rear-left"||v==="rear-right"?"rear":v==="left"?"left":v==="right"?"right":null;
const area=p=>{if(!p||p.length<3)return 0;let a=0;for(let i=0;i<p.length;i++){const q=p[(i+1)%p.length];a+=p[i].x*q.y-q.x*p[i].y}return Math.abs(a/2)};
export async function onRequestPost({request,env}){try{const b=await request.json().catch(()=>({})),id=safe(b.projectId);if(!id)return json({error:"projectId required"},400);const pipe=await read(env,id+"/_pipeline.json",null),g=await read(env,id+"/_geometry.json",{photos:{}}),v=await read(env,id+"/_verified.json",null),p=await read(env,id+"/_project.json",{photoViews:{}});if(!pipe)return json({error:"Process Property first."},400);if(!v)return json({error:"Preserve verified objects first."},400);
let vp=Array.isArray(v.photos)?v.photos:Object.entries(v.photos||{}).map(([key,x])=>Object.assign({key},x||{})),by=new Map(vp.map(x=>[x.key||x.photoKey,x]));const elevations={};
for(const name of ["front","right","rear","left"]){const c=Object.entries(p.photoViews||{}).filter(([,view])=>canon(view)===name).map(([key,view])=>({key,view,shapes:g.photos?.[key]||[],photo:by.get(key)})).filter(x=>x.shapes.some(s=>s.type==="wall")),src=c.find(x=>x.view===name)||c[0];if(!src){elevations[name]={status:"missing"};continue}const walls=src.shapes.filter(s=>s.type==="wall"),det=src.photo?.detections||{},opens=[...(det.window||[]),...(det.door||[])];elevations[name]={status:pipe.elevations?.[name]?.status||"limited",sourceKey:src.key,sourceView:src.view,wallPlanes:walls.length,grossNormalized:Number(walls.reduce((n,w)=>n+area(w.points),0).toFixed(6)),openingNormalized:Number(opens.reduce((n,o)=>n+Math.abs((+o.x2-+o.x1)*(+o.y2-+o.y1)),0).toFixed(6)),windows:(det.window||[]).length,doors:(det.door||[]).length,gables:src.shapes.filter(s=>s.type==="gable").length}}
const out={version:2,createdAt:new Date().toISOString(),projectId:id,confidence:pipe.confidence,elevations,metricReady:false};await env.MEASURE_PHOTOS.put(id+"/_house_model.json",JSON.stringify(out),{httpMetadata:{contentType:"application/json"}});return json({ok:true,houseModel:out})}catch(e){return json({error:e?.message||String(e)},500)}}
export async function onRequestGet({request,env}){const id=safe(new URL(request.url).searchParams.get("projectId"));return json({houseModel:id?await read(env,id+"/_house_model.json",null):null})}